// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA196y6aiBZWOuBUrhF1cD_DT0rbh3qZHQ',
    appId: '1:870690421996:web:c73e6685caad05d52979c9',
    messagingSenderId: '870690421996',
    projectId: 'flutter-chat-app-18fc7',
    authDomain: 'flutter-chat-app-18fc7.firebaseapp.com',
    storageBucket: 'flutter-chat-app-18fc7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-CMcIKs6-5Ct3XZZ0hIn9rgCnT2JyBlI',
    appId: '1:870690421996:android:8e2addcc6ea98b712979c9',
    messagingSenderId: '870690421996',
    projectId: 'flutter-chat-app-18fc7',
    storageBucket: 'flutter-chat-app-18fc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyzOQbvSyK86hA0rc5wRMVpKDZGYwnHCA',
    appId: '1:870690421996:ios:73df8c342abce85b2979c9',
    messagingSenderId: '870690421996',
    projectId: 'flutter-chat-app-18fc7',
    storageBucket: 'flutter-chat-app-18fc7.firebasestorage.app',
    iosBundleId: 'com.example.myChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyzOQbvSyK86hA0rc5wRMVpKDZGYwnHCA',
    appId: '1:870690421996:ios:73df8c342abce85b2979c9',
    messagingSenderId: '870690421996',
    projectId: 'flutter-chat-app-18fc7',
    storageBucket: 'flutter-chat-app-18fc7.firebasestorage.app',
    iosBundleId: 'com.example.myChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA196y6aiBZWOuBUrhF1cD_DT0rbh3qZHQ',
    appId: '1:870690421996:web:f74211dc9b75e4db2979c9',
    messagingSenderId: '870690421996',
    projectId: 'flutter-chat-app-18fc7',
    authDomain: 'flutter-chat-app-18fc7.firebaseapp.com',
    storageBucket: 'flutter-chat-app-18fc7.firebasestorage.app',
  );
}
